/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
AssetsRes._();
  static const String PLUGIN_NAME = 'complete_advanced_flutter';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ONBOARDING_LOGO1 = 'assets/images/onboarding_logo1.svg';
  static const String ONBOARDING_LOGO2 = 'assets/images/onboarding_logo2.svg';
  static const String ONBOARDING_LOGO3 = 'assets/images/onboarding_logo3.svg';
  static const String ONBOARDING_LOGO4 = 'assets/images/onboarding_logo4.svg';
  static const String SPLASH_LOGO = 'assets/images/splash_logo.png';
}
